const actionsTypes = {
    PROFILE_REQUEST_GET_USER: 'PROFILE_REQUEST_GET_USER',
    PROFILE_REQUEST_REMOVE_USER: 'PROFILE_REQUEST_REMOVE_USER',
    PROFILE_REQUEST_UPDATE_PASSWORD: 'PROFILE_REQUEST_UPDATE_PASSWORD',
    PROFILE_REQUEST_UPDATE_USER: 'PROFILE_REQUEST_UPDATE_USER',
    PROFILE_SET_LOADING: 'PROFILE_SET_LOADING',
    PROFILE_SET_USER: 'PROFILE_SET_USER',
}

export { actionsTypes }
