const actionsTypes = {
    AUTH_LOADING: 'AUTH_LOADING',
    AUTH_REQUEST_CONFIRM_CODE: 'AUTH_REQUEST_CONFIRM_CODE',
    AUTH_REQUEST_FORGOT_PASSWORD: 'AUTH_REQUEST_FORGOT_PASSWORD',
    AUTH_REQUEST_RESEND_CODE: 'AUTH_REQUEST_RESEND_CODE',
    AUTH_REQUEST_RESET_PASSWORD: 'AUTH_REQUEST_RESET_PASSWORD',
    AUTH_REQUEST_SIGN_IN: 'AUTH_REQUEST_SIGN_IN',
    AUTH_REQUEST_SIGN_UP: 'AUTH_REQUEST_SIGN_UP',
}

export { actionsTypes }
