const actionsTypes = {
    COURSE_REQUEST_GET_COURSES: 'COURSE_REQUEST_GET_COURSES',
    COURSE_SET_COURSES: 'COURSE_SET_COURSES',
    COURSE_SET_LOADING: 'COURSE_SET_LOADING',
}

export { actionsTypes }
