const actionsTypes = {
    COURSE_REMOVE_COURSE: 'COURSE_REMOVE_COURSE',
    COURSE_REQUEST_GET_COURSE: 'COURSE_REQUEST_GET_COURSE',
    COURSE_REQUEST_GET_COURSES: 'COURSE_REQUEST_GET_COURSES',
    COURSE_REQUEST_REMOVE_COURSE: 'COURSE_REQUEST_REMOVE_COURSE',
    COURSE_REQUEST_SAVE_COURSE: 'COURSE_REQUEST_SAVE_COURSE',
    COURSE_SET_COURSE: 'COURSE_SET_COURSE',
    COURSE_SET_COURSES: 'COURSE_SET_COURSES',
    COURSE_SET_LOADING: 'COURSE_SET_LOADING',
}

export { actionsTypes }
